<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.eurotech.framework.log</groupId>
    <artifactId>log4j-systemd-journal-appender</artifactId>
    <name>log4j-systemd-journal-appender</name>
    <version>1.1.0-SNAPSHOT</version>
    <packaging>bundle</packaging>
    <properties>
        <maven.compiler.target>21</maven.compiler.target>
        <maven.compiler.source>21</maven.compiler.source>
        <skip.artifact.signing>true</skip.artifact.signing>
        <log4j.version>2.25.3</log4j.version>
        <junixsocket.version>2.10.1</junixsocket.version>
    </properties>
    <profiles>
        <profile>
            <id>sign-artifacts</id>
            <properties>
                <skip.artifact.signing>false</skip.artifact.signing>
            </properties>
        </profile>
    </profiles>
    <dependencies>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.crac</groupId>
            <artifactId>crac</artifactId>
            <version>1.5.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.kohlschutter.junixsocket</groupId>
            <artifactId>junixsocket-native-common</artifactId>
            <version>${junixsocket.version}</version>
        </dependency>
        <dependency>
            <groupId>com.kohlschutter.junixsocket</groupId>
            <artifactId>junixsocket-common</artifactId>
            <version>${junixsocket.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>2.28.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>2.17</version>
                <executions>
                    <execution>
                        <id>checkstyle-validation</id>
                        <phase>process-sources</phase>
                        <configuration>
                            <skip>true</skip>
                        </configuration>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <version>6.0.2</version>
                <extensions>true</extensions>
                <configuration>
                    <manifestLocation>META-INF</manifestLocation>
                    <instructions>
                        <Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
                        <Bundle-Name>${project.artifactId}</Bundle-Name>
                        <Bundle-Version>${project.version}</Bundle-Version>
                        <Embed-Dependency>junixsocket-native-common,junixsocket-common</Embed-Dependency>
                        <Fragment-Host>org.apache.logging.log4j.api</Fragment-Host>
                        <Include-Resource>${project.build.directory}/classes/</Include-Resource>
                        <Export-Package>de.bwaldvogel</Export-Package>
                        <Import-Package>
                            org.apache.logging.log4j.core.*,
                            org.crac;resolution:=optional
                        </Import-Package>
                    </instructions>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jarsigner-plugin</artifactId>
                <version>1.4</version>
                <executions>
                    <execution>
                        <id>sign</id>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <skip>${skip.artifact.signing}</skip>
                    <storetype>${keystore.type}</storetype>
                    <keystore>${bundle.keystore.path}</keystore>
                    <alias>${bundle.key.alias}</alias>
                    <storepass>${bundle.keystore.password}</storepass>
                    <keypass>${bundle.key.password}</keypass>
                    <arguments>
                        <argument>-tsa</argument>
                        <argument>http://timestamp.digicert.com</argument>
                    </arguments>
                    <archiverConfig>
                        <compress>false</compress>
                    </archiverConfig>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>.</directory>
                <includes>
                    <include>LICENSE.txt</include>
                </includes>
                <targetPath>.</targetPath>
            </resource>
        </resources>
    </build>
    <distributionManagement>
        <repository>
            <id>artifactory-esf-release</id>
            <name>Eurotech Artifactory Repository - Releases</name>
            <url>https://artifactory.everyware-cloud.com/artifactory/esf-release</url>
        </repository>
        <snapshotRepository>
            <id>artifactory-esf-snapshot</id>
            <name>Eurotech Artifactory Repository - Snapshots</name>
            <url>https://artifactory.everyware-cloud.com/artifactory/esf-snapshot</url>
        </snapshotRepository>
    </distributionManagement>
</project>
